joint_limits:
  base: {has_velocity_limits: true, max_velocity: 0.35, has_acceleration_limits: true, max_acceleration: 0.5}
  shoulder: {has_velocity_limits: true, max_velocity: 0.35, has_acceleration_limits: true, max_acceleration: 0.5}
  elbow: {has_velocity_limits: true, max_velocity: 0.35, has_acceleration_limits: true, max_acceleration: 0.5}
  wrist1: {has_velocity_limits: true, max_velocity: 0.35, has_acceleration_limits: true, max_acceleration: 0.5}
  wrist2: {has_velocity_limits: true, max_velocity: 0.35, has_acceleration_limits: true, max_acceleration: 0.5}
  wrist3: {has_velocity_limits: true, max_velocity: 0.35, has_acceleration_limits: true, max_acceleration: 0.5}
